version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_PROD=${REACT_APP_PROD}
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - CLIENT=${CLIENT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      - OIDC_ISSUER=${OIDC_ISSUER}
      - OIDC_AUTH_URL=${OIDC_AUTH_URL}
      - OIDC_TOKEN_URL=${OIDC_TOKEN_URL}
      - OIDC_USERINFO_URL=${OIDC_USERINFO_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - TODOIST_CLIENT_ID=${TODOIST_CLIENT_ID}
      - TODOIST_CLIENT_SECRET=${TODOIST_CLIENT_SECRET}
      - TODOIST_REDIRECT_URL=${TODOIST_REDIRECT_URL}
      - TICKTICK_CLIENT_ID=${TICKTICK_CLIENT_ID}
      - TICKTICK_CLIENT_SECRET=${TICKTICK_CLIENT_SECRET}
      - TICKTICK_REDIRECT_URL=${TICKTICK_REDIRECT_URL}
      